package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Autores generated by hbm2java
 */
public class Autor implements java.io.Serializable {

    private Integer codigo;
    private String apellido;
    private String nombre;
    private Set pubAuts = new HashSet(0);

    public Autor() {
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getPubAuts() {
        return this.pubAuts;
    }

    public void setPubAuts(Set pubAuts) {
        this.pubAuts = pubAuts;
    }

}
