package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clasificaciones generated by hbm2java
 */
public class Clasificaciones  implements java.io.Serializable {


     private Integer claCodigo;
     private int claIdentificador;
     private String claDescripcion;
     private Set pubClas = new HashSet(0);

    public Clasificaciones() {
    }

	
    public Clasificaciones(int claIdentificador, String claDescripcion) {
        this.claIdentificador = claIdentificador;
        this.claDescripcion = claDescripcion;
    }
    public Clasificaciones(int claIdentificador, String claDescripcion, Set pubClas) {
       this.claIdentificador = claIdentificador;
       this.claDescripcion = claDescripcion;
       this.pubClas = pubClas;
    }
   
    public Integer getClaCodigo() {
        return this.claCodigo;
    }
    
    public void setClaCodigo(Integer claCodigo) {
        this.claCodigo = claCodigo;
    }
    public int getClaIdentificador() {
        return this.claIdentificador;
    }
    
    public void setClaIdentificador(int claIdentificador) {
        this.claIdentificador = claIdentificador;
    }
    public String getClaDescripcion() {
        return this.claDescripcion;
    }
    
    public void setClaDescripcion(String claDescripcion) {
        this.claDescripcion = claDescripcion;
    }
    public Set getPubClas() {
        return this.pubClas;
    }
    
    public void setPubClas(Set pubClas) {
        this.pubClas = pubClas;
    }




}


