package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetallesPrestamos generated by hbm2java
 */
public class DetallesPrestamos  implements java.io.Serializable {


     private Integer dpCodigo;
     private Prestamos prestamos;
     private Publicacion publicaciones;
     private boolean dpEstado;
     private Date dpFechaADevolver;
     private String dpTurno;
     private Date dpFechaDevolucion;

    public DetallesPrestamos() {
    }

    public DetallesPrestamos(Prestamos prestamos, Publicacion publicaciones, boolean dpEstado, Date dpFechaADevolver, String dpTurno, Date dpFechaDevolucion) {
       this.prestamos = prestamos;
       this.publicaciones = publicaciones;
       this.dpEstado = dpEstado;
       this.dpFechaADevolver = dpFechaADevolver;
       this.dpTurno = dpTurno;
       this.dpFechaDevolucion = dpFechaDevolucion;
    }
   
    public Integer getDpCodigo() {
        return this.dpCodigo;
    }
    
    public void setDpCodigo(Integer dpCodigo) {
        this.dpCodigo = dpCodigo;
    }
    public Prestamos getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Prestamos prestamos) {
        this.prestamos = prestamos;
    }
    public Publicacion getPublicaciones() {
        return this.publicaciones;
    }
    
    public void setPublicaciones(Publicacion publicaciones) {
        this.publicaciones = publicaciones;
    }
    public boolean isDpEstado() {
        return this.dpEstado;
    }
    
    public void setDpEstado(boolean dpEstado) {
        this.dpEstado = dpEstado;
    }
    public Date getDpFechaADevolver() {
        return this.dpFechaADevolver;
    }
    
    public void setDpFechaADevolver(Date dpFechaADevolver) {
        this.dpFechaADevolver = dpFechaADevolver;
    }
    public String getDpTurno() {
        return this.dpTurno;
    }
    
    public void setDpTurno(String dpTurno) {
        this.dpTurno = dpTurno;
    }
    public Date getDpFechaDevolucion() {
        return this.dpFechaDevolucion;
    }
    
    public void setDpFechaDevolucion(Date dpFechaDevolucion) {
        this.dpFechaDevolucion = dpFechaDevolucion;
    }




}


