package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1



/**
 * DetallesReservas generated by hbm2java
 */
public class DetallesReservas  implements java.io.Serializable {


     private Integer drevCodigo;
     private Publicacion publicaciones;
     private Reservas reservas;
     private int drevCantidad;
     private boolean drevEstado;

    public DetallesReservas() {
    }

    public DetallesReservas(Publicacion publicaciones, Reservas reservas, int drevCantidad, boolean drevEstado) {
       this.publicaciones = publicaciones;
       this.reservas = reservas;
       this.drevCantidad = drevCantidad;
       this.drevEstado = drevEstado;
    }
   
    public Integer getDrevCodigo() {
        return this.drevCodigo;
    }
    
    public void setDrevCodigo(Integer drevCodigo) {
        this.drevCodigo = drevCodigo;
    }
    public Publicacion getPublicaciones() {
        return this.publicaciones;
    }
    
    public void setPublicaciones(Publicacion publicaciones) {
        this.publicaciones = publicaciones;
    }
    public Reservas getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Reservas reservas) {
        this.reservas = reservas;
    }
    public int getDrevCantidad() {
        return this.drevCantidad;
    }
    
    public void setDrevCantidad(int drevCantidad) {
        this.drevCantidad = drevCantidad;
    }
    public boolean isDrevEstado() {
        return this.drevEstado;
    }
    
    public void setDrevEstado(boolean drevEstado) {
        this.drevEstado = drevEstado;
    }




}


