package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DetallesPrestamos generated by hbm2java
 */
public class DetallePrestamo implements java.io.Serializable {

    private Integer codigo;
    private Prestamo prestamo;
    private Publicacion publicacion;
    private boolean estado;
    private Date fechaADevolver;
    private String turno;
    private Date fechaDevolucion;

    public DetallePrestamo() {
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Prestamo getPrestamo() {
        return prestamo;
    }

    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }

    public Publicacion getPublicacion() {
        return publicacion;
    }

    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public Date getFechaADevolver() {
        return fechaADevolver;
    }

    public void setFechaADevolver(Date fechaADevolver) {
        this.fechaADevolver = fechaADevolver;
    }

    public String getTurno() {
        return turno;
    }

    public void setTurno(String turno) {
        this.turno = turno;
    }

    public Date getFechaDevolucion() {
        return fechaDevolucion;
    }

    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }

}
