package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private Integer preCodigo;
     private Perfil perfiles;
     private Date preFechaPrestamo;
     private boolean preEstado;
     private String preAdministrativo;
     private Set detallesPrestamoses = new HashSet(0);

    public Prestamos() {
    }

	
    public Prestamos(Perfil perfiles, Date preFechaPrestamo, boolean preEstado, String preAdministrativo) {
        this.perfiles = perfiles;
        this.preFechaPrestamo = preFechaPrestamo;
        this.preEstado = preEstado;
        this.preAdministrativo = preAdministrativo;
    }
    public Prestamos(Perfil perfiles, Date preFechaPrestamo, boolean preEstado, String preAdministrativo, Set detallesPrestamoses) {
       this.perfiles = perfiles;
       this.preFechaPrestamo = preFechaPrestamo;
       this.preEstado = preEstado;
       this.preAdministrativo = preAdministrativo;
       this.detallesPrestamoses = detallesPrestamoses;
    }
   
    public Integer getPreCodigo() {
        return this.preCodigo;
    }
    
    public void setPreCodigo(Integer preCodigo) {
        this.preCodigo = preCodigo;
    }
    public Perfil getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfil perfiles) {
        this.perfiles = perfiles;
    }
    public Date getPreFechaPrestamo() {
        return this.preFechaPrestamo;
    }
    
    public void setPreFechaPrestamo(Date preFechaPrestamo) {
        this.preFechaPrestamo = preFechaPrestamo;
    }
    public boolean isPreEstado() {
        return this.preEstado;
    }
    
    public void setPreEstado(boolean preEstado) {
        this.preEstado = preEstado;
    }
    public String getPreAdministrativo() {
        return this.preAdministrativo;
    }
    
    public void setPreAdministrativo(String preAdministrativo) {
        this.preAdministrativo = preAdministrativo;
    }
    public Set getDetallesPrestamoses() {
        return this.detallesPrestamoses;
    }
    
    public void setDetallesPrestamoses(Set detallesPrestamoses) {
        this.detallesPrestamoses = detallesPrestamoses;
    }




}


