package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1



/**
 * PubAut generated by hbm2java
 */
public class PubAut  implements java.io.Serializable {


     private Integer codigo;
     private Autor autor;
     private Publicacion publicacion;
     private boolean paEstado;

    public PubAut() {
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Autor getAutor() {
        return autor;
    }

    public void setAutor(Autor autor) {
        this.autor = autor;
    }

 
    public Publicacion getPublicacion() {
        return publicacion;
    }

    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }

   
    public boolean isPaEstado() {
        return this.paEstado;
    }
    
    public void setPaEstado(boolean paEstado) {
        this.paEstado = paEstado;
    }




}


