package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1



/**
 * PubCla generated by hbm2java
 */
public class PubCla  implements java.io.Serializable {


     private Integer pcCodigo;
     private Clasificaciones clasificaciones;
     private Publicacion publicaciones;
     private boolean pcEstado;

    public PubCla() {
    }

    public PubCla(Clasificaciones clasificaciones, Publicacion publicaciones, boolean pcEstado) {
       this.clasificaciones = clasificaciones;
       this.publicaciones = publicaciones;
       this.pcEstado = pcEstado;
    }
   
    public Integer getPcCodigo() {
        return this.pcCodigo;
    }
    
    public void setPcCodigo(Integer pcCodigo) {
        this.pcCodigo = pcCodigo;
    }
    public Clasificaciones getClasificaciones() {
        return this.clasificaciones;
    }
    
    public void setClasificaciones(Clasificaciones clasificaciones) {
        this.clasificaciones = clasificaciones;
    }
    public Publicacion getPublicaciones() {
        return this.publicaciones;
    }
    
    public void setPublicaciones(Publicacion publicaciones) {
        this.publicaciones = publicaciones;
    }
    public boolean isPcEstado() {
        return this.pcEstado;
    }
    
    public void setPcEstado(boolean pcEstado) {
        this.pcEstado = pcEstado;
    }




}


