package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicacion  implements java.io.Serializable {


     private String codigo;
     private Editorial editorial;
     private String nombre;
     private String resumen;
     private boolean estado;
     private String tipo;
     private int stock;
     private Set detallesReservases = new HashSet(0);
     private Set pubClas = new HashSet(0);
     private Set detallesPrestamoses = new HashSet(0);
     private Set pubAuts = new HashSet(0);

    public Publicacion() {
    }

    public Publicacion(String codigo, Editorial editorial, String nombre, String resumen, boolean estado, String tipo, int stock) {
        this.codigo = codigo;
        this.editorial = editorial;
        this.nombre = nombre;
        this.resumen = resumen;
        this.estado = estado;
        this.tipo = tipo;
        this.stock = stock;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Editorial getEditorial() {
        return editorial;
    }

    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getResumen() {
        return resumen;
    }

    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

	
    public Set getDetallesReservases() {
        return this.detallesReservases;
    }
    
    public void setDetallesReservases(Set detallesReservases) {
        this.detallesReservases = detallesReservases;
    }
    public Set getPubClas() {
        return this.pubClas;
    }
    
    public void setPubClas(Set pubClas) {
        this.pubClas = pubClas;
    }
    public Set getDetallesPrestamoses() {
        return this.detallesPrestamoses;
    }
    
    public void setDetallesPrestamoses(Set detallesPrestamoses) {
        this.detallesPrestamoses = detallesPrestamoses;
    }
    public Set getPubAuts() {
        return this.pubAuts;
    }
    
    public void setPubAuts(Set pubAuts) {
        this.pubAuts = pubAuts;
    }




}


