package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservas generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer codigo;
     private Perfil perfil;
     private Date fechaEmision;
     private Date fechaTurno;
     private boolean estado;
     private Set detallesReservases = new HashSet(0);

    public Reserva() {
        
    }

    public Reserva(Date fechaEmision, boolean estado) {
        this.fechaEmision = fechaEmision;
        this.estado = estado;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public Perfil getPerfil() {
        return perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    public Date getFechaEmision() {
        return fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    public Date getFechaTurno() {
        return fechaTurno;
    }

    public void setFechaTurno(Date fechaTurno) {
        this.fechaTurno = fechaTurno;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }


    public Set getDetallesReservases() {
        return this.detallesReservases;
    }
    
    public void setDetallesReservases(Set detallesReservases) {
        this.detallesReservases = detallesReservases;
    }




}


